name: Daily Trading Bot

on:
  schedule:
    - cron: "30 3 * * *"  # Every day at 9:00 AM IST (03:30 UTC)
  workflow_dispatch:      # Manual trigger

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance ta pandas scikit-learn python-telegram-bot

      - name: Run your bot
        run: |
          python your_bot_file.py  # 🔁 Replace with your actual file name
          
