name: Daily Trading Bot

on:
  schedule:
    - cron: "0 3 * * *"  # Runs every day at 8:30 AM IST
  workflow_dispatch:

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run notebook
      run: |
        pip install jupyter nbconvert
        jupyter nbconvert --to notebook --execute Trading_bot.ipynb
        
