name: Daily Trading Signal

on:
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 2 AM UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run notebook
        run: |
          pip install notebook
          jupyter nbconvert --to notebook --execute Trading_bot.ipynb --output executed_notebook.ipynb
